reference1: &allCodeFiles
  - "**/*.swift"

name: MomentCart
options:
  bundleIdPrefix: com.navercorp
  deploymentTarget:
    iOS: 11.0
  findCarthageFrameworks: true
  createIntermediateGroups: true
settings:
  base:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
targets:
  # App
  MomentApp:
    type: application
    platform: iOS
    deploymentTarget: 13.0
    dependencies:
      - target: MomentCommon
      - target: MomentEditor
      - target: MomentPlayer
      - carthage: Alamofire
    sources:
      - path: Sample/MomentApp/MomentApp
        createIntermediateGroups: false
    settings:
      base:
        DEVELOPMENT_TEAM: K4WL5WK33A
  # Common
  MomentCommon:
    type: framework
    platform: iOS
    dependencies:
      - target: MomentCommonUtil
        link: true
    sources:
      - path: Sources/Common/MomentCommon
    settings:
      base:
        INFOPLIST_FILE: Supporting Files/Framework_Info.plist
    scheme:
      testTargets:
        - MomentCommonTests
  MomentCommonTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: MomentCommon
    sources:
      - path: Tests/Common/MomentCommonTests
    settings:
      base:
        INFOPLIST_FILE: Supporting Files/Framework_Info.plist
  MomentCommonUtil:
    type: library.static
    platform: iOS
    sources:
      - path: Sources/Common/Util
  # Editor
  MomentEditor:
    type: framework
    platform: iOS
    dependencies:
      - target: MomentEditorDomain
        link: true
      - target: MomentEditorView
        link: true
      - target: MomentEditorRepository
        link: true
      - target: MomentSDK_MomentEditorView
        embed: true
      - carthage: Alamofire
    sources:
      - path: Sources/Editor/MomentEditor
    settings:
      base:
        INFOPLIST_FILE: Supporting Files/Framework_Info.plist
    scheme:
      testTargets:
        - MomentEditorTests
  MomentEditorTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: MomentEditor
    sources:
      - path: Tests/Editor/MomentEditorTests
    settings:
      base:
        INFOPLIST_FILE: Supporting Files/Framework_Info.plist
  MomentEditorDomain:
    type: library.static
    platform: iOS
    dependencies:
      - target: MomentCommonUtil
    sources:
      - path: Sources/Editor/Domain
    scheme:
      testTargets:
        - MomentEditorDomainTests
  MomentEditorDomainTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: MomentEditorDomain
    sources:
      - path: Tests/Editor/DomainTests
    settings:
      base:
        INFOPLIST_FILE: Supporting Files/Framework_Info.plist
  MomentEditorView:
    type: library.static
    platform: iOS
    dependencies:
      - target: MomentEditorDomain
      - target: MomentCommonUtil
      - target: MomentSDK_MomentEditorView
      - carthage: Alamofire
    sources:
      - path: Sources/Editor/View
        includes: *allCodeFiles
  MomentSDK_MomentEditorView:
    type: bundle
    platform: iOS
    sources:
      - path: Sources/Editor/View
        excludes: *allCodeFiles
    settings:
      base:
        INFOPLIST_FILE: Supporting Files/Bundle_Info.plist
  MomentEditorRepository:
    type: library.static
    platform: iOS
    dependencies:
      - target: MomentEditorDomain
      - carthage: Alamofire
    sources:
      - path: Sources/Editor/Repository
    scheme:
      testTargets:
        - MomentEditorRepositoryTests
  MomentEditorRepositoryTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: MomentEditorRepository
    sources:
      - path: Tests/Editor/RepositoryTests
    settings:
      base:
        INFOPLIST_FILE: Supporting Files/Framework_Info.plist
  # Player
  MomentPlayer:
    type: framework
    platform: iOS
    dependencies:
      - target: MomentPlayerDomain
        link: true
      - target: MomentPlayerView
        link: true
      - target: MomentPlayerRepository
        link: true
      - carthage: Alamofire
    sources:
      - path: Sources/Player/MomentPlayer
    settings:
      base:
        INFOPLIST_FILE: Supporting Files/Framework_Info.plist
    scheme:
      testTargets:
        - MomentPlayerTests
  MomentPlayerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/Player/MomentPlayerTests
    dependencies:
      - target: MomentPlayer
    settings:
      base:
        INFOPLIST_FILE: Supporting Files/Framework_Info.plist
  MomentPlayerDomain:
    type: library.static
    platform: iOS
    sources:
      - path: Sources/Player/Domain
    scheme:
      testTargets:
        - MomentPlayerDomainTests
  MomentPlayerDomainTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: MomentPlayerDomain
    sources:
      - path: Tests/Player/DomainTests
    settings:
      base:
        INFOPLIST_FILE: Supporting Files/Framework_Info.plist
  MomentPlayerView:
    type: library.static
    platform: iOS
    dependencies:
      - target: MomentPlayerDomain
      - target: MomentCommonUtil
    sources:
      - path: Sources/Player/View
  MomentPlayerRepository:
    type: library.static
    platform: iOS
    dependencies:
      - target: MomentPlayerDomain
    sources:
      - path: Sources/Player/Repository
    scheme:
      testTargets:
        - MomentPlayerRepositoryTests
  MomentPlayerRepositoryTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: MomentPlayerRepository
    sources:
      - path: Tests/Player/RepositoryTests
    settings:
      base:
        INFOPLIST_FILE: Supporting Files/Framework_Info.plist
